[workspace]
authors = ["udit-asopa <udit.asopa@gmail.com>"]
channels = ["conda-forge"]
name = "food_recommendation_with_chromadb"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
sentence-transformers = ">=5.1.2,<6"
pytorch = ">=2.8.0,<3"
accelerate = ">=1.11.0,<2"
optimum = ">=2.0.0,<3"
tokenizers = ">=0.22.1,<0.23"
bitsandbytes = ">=0.48.2,<0.49"
transformers = ">=4.57.1,<5"
chromadb = ">=1.0.20,<2"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.4,<3"
click = ">=8.3.0,<9"
rich = ">=14.2.0,<15"
typer = ">=0.20.0,<0.21"
langchain-community = ">=0.3.31,<0.4"
datasets = ">=4.3.0,<5"
langchain = ">=1.0.3,<2"
